# Generated by Django 3.1.7 on 2021-04-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='entry',
            name='currency',
            field=models.CharField(choices=[('PLN', 'Polski Złoty'), ('EUR', 'Euro'), ('USD', 'American Dollar')], default='PLN', max_length=3),
        ),
    ]
